
spring :
  datasource :
    username : sa
    password : 1234
    url : jdbc:sqlserver://localhost:1433;databaseName=movies;instanceName=Jeevan;encrypt=true;trustServerCertificate=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: